version: '3'
services:
  loadbalancer:
    build:
      context:  .
      dockerfile: Dockerfile-nginx
    ports:
      - "8080:80"
    volumes:
        - ./config:/var/www/html/config
        - ./data:/var/www/html/data
        - ./public:/var/www/html/public
        - ./src:/var/www/html/src
        - ./vendor:/var/www/html/vendor
    links:
      - socket01
      - socket02
      - fpm

  socket01:
    build:
      context:  .
      dockerfile: Dockerfile-socketio
    volumes:
      - .:/app
    expose:
      - "3000"
    command: ["node", "/app/sockets/start.js"]
    environment:
      - LABEL=SocketServer01
    links:
      - redis

  socket02:
    build:
      context:  .
      dockerfile: Dockerfile-socketio
    volumes:
      - .:/app
    expose:
      - "3000"
    command: ["node", "/app/sockets/start.js"]
    environment:
      - LABEL=SocketServer02
    links:
      - redis

  redis:
    image: redis:3.2
    volumes:
      - ./redis-data/:/data

  fpm:
    image: php:7.2-fpm
    volumes:
        - ./config:/var/www/html/config
        - ./data:/var/www/html/data
        - ./public:/var/www/html/public
        - ./src:/var/www/html/src
        - ./vendor:/var/www/html/vendor
