version: '3'
services:
  loadbalancer:
    build:
      context:  .
      dockerfile: Dockerfile-nginx
    image: loadbalancesocketio_loadbalancer:latest
    ports:
      - "8080:80"
    volumes:
        - ./config:/var/www/html/config
        - ./data:/var/www/html/data
        - ./public:/var/www/html/public
        - ./src:/var/www/html/src
        - ./vendor:/var/www/html/vendor
    links:
      - socket01
      - socket02
      - socket03
      - socket04
      - socket05
      - fpm

  socket01:
    build:
      context:  .
      dockerfile: Dockerfile-socketio
    image: loadbalancesocketio_socket:latest
    volumes:
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./sockets:/app/sockets
    expose:
      - "3000"
    environment:
      - LABEL=SocketServer01
    links:
      - redis

  socket02:
    build:
      context:  .
      dockerfile: Dockerfile-socketio
    image: loadbalancesocketio_socket:latest
    volumes:
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./sockets:/app/sockets
    expose:
      - "3000"
    environment:
      - LABEL=SocketServer02
    links:
      - redis

  socket03:
    build:
      context:  .
      dockerfile: Dockerfile-socketio
    image: loadbalancesocketio_socket:latest
    volumes:
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./sockets:/app/sockets
    expose:
      - "3000"
    environment:
      - LABEL=SocketServer03
    links:
      - redis

  socket04:
    build:
      context:  .
      dockerfile: Dockerfile-socketio
    image: loadbalancesocketio_socket:latest
    volumes:
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./sockets:/app/sockets
    expose:
      - "3000"
    environment:
      - LABEL=SocketServer04
    links:
      - redis

  socket05:
    build:
      context:  .
      dockerfile: Dockerfile-socketio
    image: loadbalancesocketio_socket:latest
    volumes:
      - ./node_modules:/app/node_modules
      - ./package.json:/app/package.json
      - ./sockets:/app/sockets
    expose:
      - "3000"
    environment:
      - LABEL=SocketServer05
    links:
      - redis

  redis:
    image: redis:3.2
    volumes:
      - ./redis-data/:/data

  fpm:
    image: php:7.2-fpm
    volumes:
        - ./config:/var/www/html/config
        - ./data:/var/www/html/data
        - ./public:/var/www/html/public
        - ./src:/var/www/html/src
        - ./vendor:/var/www/html/vendor
